---
title: "lesson8_problemset"
author: "Arthur Chaves"
date: "26/08/2019"
output: html_document
---

```{r Price Histograms with Facet and Color}
library(ggplot2)
library(dplyr)
data(diamonds)
ggplot(aes(x=log(price)),data=diamonds)+
  geom_histogram(aes(fill=cut))+
  scale_fill_brewer(type='qual')+
  facet_wrap(~color)
```

```{r Price vs Table colored by cut}
ggplot(aes(x=table,y=price),data=diamonds)+
  geom_point(aes(color=cut))+
  scale_color_brewer(type='qual')
```

```{r Price vs Volume and Diamond Clarity}
ggplot(aes(x=x*y*z,y=price),data=diamonds)+
  scale_y_log10()+
  scale_color_brewer(type = 'div')+
  geom_point(aes(color=clarity))+
  xlab('volume')+
  xlim(0,quantile(diamonds$x*diamonds$y*diamonds$z,probs=0.99))
```

```{r Proportion of Friendships Initiated}
pf$prop_initiated<-pf$friendships_initiated/pf$friend_count
```

```{r prop_initiated vs tenure}
ggplot(aes(x=tenure,y=prop_initiated),data=subset(pf,
                                                  !is.na(year_joined.bucket)))+
  geom_line(stat='summary',aes(color=year_joined.bucket))
```

```{r Smoothing prop_initiated vs tenure}
ggplot(aes(x=tenure,y=prop_initiated),data=subset(pf,
                                                  !is.na(year_joined.bucket)))+
  geom_line(stat='summary',aes(color=year_joined.bucket))+
  geom_smooth()
```

```{r Group's average proportion of friendships initiated}
summary(subset(pf,'year_joined.bucket'='(2012,2014]')$prop_initiated)['Mean']
```

```{r Price/Carat Binned, Faceted & Colored}
ggplot(aes(y=price/carat,x=cut),data=diamonds)+
  geom_jitter(aes(color=color))+
  facet_wrap(~clarity)+
  scale_color_brewer(type='div')
```

